version: '3'
services:
  ethereum:
    image: parity/parity:latest
    volumes:
      - ./dev-chain/chain.json:/home/parity/.local/share/io.parity.ethereum/chain.json
      - ./dev-chain/config.toml:/home/parity/.local/share/io.parity.ethereum/config.toml
      - ./dev-chain/keys:/home/parity/.local/share/io.parity.ethereum/keys/dev
      - ./dev-chain/pass.txt:/home/parity/.local/share/io.parity.ethereum/pass.txt
    #command: --config /home/parity/.local/share/io.parity.ethereum/config.toml --jsonrpc-cors all --jsonrpc-interface all --jsonrpc-apis all --jsonrpc-hosts all --tracing on --pruning archive -l rpc=trace,own_tx=trace --jsonrpc-port 8545
    command: --config /home/parity/.local/share/io.parity.ethereum/config.toml --unsafe-expose --geth --force-ui
    restart: always
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      #- 30303:30303/udp
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - ethereum
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      #ethereum: 'mainnet:http://host.docker.internal:8545'
      ethereum: 'dev:http://ethereum:8545'
      RUST_LOG: info
      GRAPH_LOG: debug
      RUST_BACKTRACE: 1
      GRAPH_ETH_CALL_BY_NUMBER: 1 # remove when EIP1898 is merged into openethereum... https://github.com/openethereum/openethereum/pull/203
  ipfs:
    image: ipfs/go-ipfs:v0.4.23
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  block-explorer:
    image: alethio/ethereum-lite-explorer
    environment:
      APP_NODE_URL: http://localhost:8545
    ports:
      - '7000:80'
