name: Deploy Graph Studio Prod

on:
  push:
    branches: master

jobs:
  deploy-studio-mainnet:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
          graph_version_label: ${GITHUB_SHA::8}
          graph_subgraph_name: "balancer-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.yaml"
          graph_deploy_studio: true
  deploy-studio-base-testnet:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
          graph_version_label: ${GITHUB_SHA::8}
          graph_subgraph_name: "balancer-base-testnet-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.basegoerli.yaml"
          graph_deploy_studio: true
  deploy-studio-sepolia:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets sepolia
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
          graph_version_label: ${GITHUB_SHA::8}
          graph_subgraph_name: "balancer-sepolia-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.sepolia.yaml"
          graph_deploy_studio: true
  deploy-studio-polygon-zkevm:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets polygon-zkevm
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
          graph_version_label: ${GITHUB_SHA::8}
          graph_subgraph_name: "balancer-polygon-zk-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.polygon-zkevm.yaml"
          graph_deploy_studio: true
  deploy-studio-base:
    runs-on: ubuntu-latest
    environment: graph
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn --frozen-lockfile
      - name: Assets
        run: yarn generate-assets base
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: balancer-labs/graph-deploy@v0.0.1
        with:
          graph_deploy_key: ${{secrets.GRAPH_DEPLOY_KEY}}
          graph_version_label: ${GITHUB_SHA::8}
          graph_subgraph_name: "balancer-base-v2"
          graph_account: "balancer-labs"
          graph_config_file: "subgraph.base.yaml"
          graph_deploy_studio: true

env:
  CI: true
